base:
  project : Wafer-Fault-Detection with Mlflow
  random_state : 355
  target_col : Output
  test_size : 0.33

app:
  host : 0.0.0.0
  port : 8080 

data_source:
  train_data_source : training_batch_files
  pred_data_source  : prediction_batch_files

data:
  good:
    train : training_good_data
    pred : prediction_good_data 
  
  bad:
    train : training_bad_data
    pred : prediction_bad_data 

mongodb:
  url: localhost:27017
  wafer_data_db_name: wafer-data
  wafer_train_data_collection: wafer-train-data
  wafer_pred_data_collection: wafer-pred-data

knn_imputer:
  n_neighbors : 3
  weights     : uniform

kmeans_cluster:
  init          : k-means++
  max_clusters  : 11
  knee_locator:
    curve     : convex
    direction : decreasing

models_dir:
  trained_models_dir : models/trained
  prod_models_dir : models/prod
  stag_models_dir : models/stag


s3_bucket:
  data_given_train_bucket: wafer-raw-data-train
  data_given_pred_bucket: wafer-raw-data-test
  data_bad_train_bucket : wafer-bad-data-train
  data_bad_pred_bucket: wafer-bad-data-pred
  data_good_train_bucket: wafer-good-data-train
  data_good_pred_bucket: wafer-good-data-pred
  schema_bucket: wafer-schema
  input_files_bucket: input-files-for-train-and-pred

model_params:
  verbose : 3
  cv      : 5
  n_jobs  : -1
  save_format : .sav

  rf_model:
    n_estimators:
      - 10
      - 50
      - 100
      - 130
      
    criterion:
      - gini
      - entropy

    max_features:
      - auto
      - log2

    max_depth:
      - 2
      - 3
      - 4
      - 5

  xgb_model:
    learning_rate:
      - 0.5
      - 0.1
      - 0.01
      - 0.001

    max_depth:
      - 3
      - 5
      - 10
      - 20

    n_estimators:
      - 10
      - 50
      - 100
      - 200
    
mlflow_config:
  experiment_name : wafer-mlflow
  remote_server_uri : 
  run_name : mlops
  serialization_format : cloudpickle
  num_of_prod_models : 3

db_log:
  db_train_log : wafer_training_logs
  db_pred_log : wafer_prediction_logs


train_db_log:
  model_training : modelTrainingLog
  col_validation : columnValidationLog
  data_transform : dataTransform
  export_csv : ExportToCsvLog
  general : GeneralLog
  db_insert: dbInsertLog
  load_prod_model : loadProdModelLog
  missing_values_in_col : missingValuesInColumn
  name_validation : nameValidationLog
  train_main : Training_Main_Log
  values_from_schema : valuesfromSchemaValidationLog


pred_db_log:
  col_validation : columnValidationLog
  db_conn: databaseConnectionLog
  data_transform : dataTransform
  db_insert : dbInsertLog
  db_create : dbTableCreateLog
  export_csv : ExportToCsvLog
  general : GeneralLog
  missing_values_in_col : missingValuesInColumn
  name_validation : nameValidationLog
  pred_main : prediction_main_log
  values_from_schema : valuesfromSchemaValidationLog

db_name:
  train_db_name: wafer_training_db
  pred_db_name: wafer_prediction_db

schema_file:
  train_schema_file : schema_training.json
  pred_schema_file : schema_prediction.json

model_names:
  xgb_model_name : XGBoost
  rf_model_name : RandomForest
  kmeans_model_name : KMeans
  
elbow_plot_fig : K-Means_Elbow.PNG

null_values_csv_file : null_values.csv

pred_output_file : predictions.csv

export_train_csv_file : train_input_file.csv

export_pred_csv_file : pred_input_file.csv

templates:
  dir : templates
  index_html_file : index.html
